### PR TITLE
refactor: use improved syncing

### PR DESCRIPTION
**Pull request by isabelroses**
closes https://github.com/auxolotl/nixpkgs/issues/7

### CODE REVIEW

**Review by jakehamilton — COMMENTED** [review]
As a part of this I think we will also need to remove the other existing workflows. Right now we have actions disabled on the repository to avoid running them since we do not have CI infrastructure set up for them to communicate with.

**Comment by isabelroses** [comment]
> As a part of this I think we will also need to remove the other existing workflows. Right now we have actions disabled on the repository to avoid running them since we do not have CI infrastructure set up for them to communicate with.

See #9, I was not 100% sure what we wanted to keep so that issue exists to hopefully help us know what we don't need.

**Comment by jakehamilton** [comment]
We should disable all non-auxolotl workflows so we don't burn through our available CI time. Can we do that either in this PR or in a follow-up?

**Review by jakehamilton — APPROVED** [review]

**Comment by isabelroses** [comment]
> We should disable all non-auxolotl workflows so we don't burn through our available CI time. Can we do that either in this PR or in a follow-up?

I shall do it in a follow up, whilst also removing the codeowners file.

**Pull request merged**
